name: Generate MGPD

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # 每 6 小时自动运行一次，可改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Run miguspeed.py
      run: python miguspeed.py

    - name: Commit MGPD.txt
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add MGPD.txt
        git commit -m "Update MGPD.txt"
        git push
