name: MGPD Auto Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build-mgpd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: cloudflare/workers-autoconfig

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Speed Test
        run: python cloudflare/workers-autoconfig/miguspeed.py

      - name: Commit MGPD.txt
        run: |
          git config user.name "MGPD Bot"
          git config user.email "bot@example.com"
          git add cloudflare/workers-autoconfig/MGPD.txt
          git commit -m "Auto update MGPD"
          git push
