name: MGPD Auto Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build-mgpd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: cloudflare/workers-autoconfig

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Speed Test
        run: python ms.py

      - name: Move MGPD into functions folder
        run: cp MGPD functions/MGPD

      - name: Commit MGPD
        run: |
          git config user.name "MGPD Bot"
          git config user.email "bot@example.com"
          if git diff --quiet functions/MGPD; then
            echo "No changes in MGPD"
          else
            git add functions/MGPD
            git commit -m "Auto update MGPD"
            git push
          fi
